name: PothcaAdmin
version: '${project.version}'
main: plugin.filled_sky24811.info.pothcaadmin.PothcaAdmin
api-version: '1.20'
default-permission: op
commands:
  pothca_admin:
    description: AdminOnly
    permission: pothcaadmin.command
    permission-message: You don't have permission!